---
- hosts: gerrit-builder
  tasks:
    - name: Remove empty directories
      command: "find {{ artifacts }} -type d -empty -delete"

    - name: Fetch artifacts
      synchronize:
        src: "{{ artifacts }}/"
        dest: "{{ zuul.executor.log_root }}/logs"
        mode: pull
      become: yes
