---
- hosts: gerrit-builder
  tasks:
    - name: Copy rpms
      copy:
        src: "/var/lib/mock/epel-7-x86_64/result"
        dest: "{{ zuul.project.src_dir }}/artifacts/build"
        remote_src: yes

    - name: Fetch artifacts
      synchronize:
        src: "{{ zuul.project.src_dir }}/artifacts/"
        dest: "{{ zuul.executor.log_root }}/logs"
        mode: pull
      become: yes
